// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxDutOV77a-qTF3msZcQmpZXYXmFyrmIo',
    appId: '1:558821628686:web:3e564bd6e596a810ea155f',
    messagingSenderId: '558821628686',
    projectId: 'viatu-f1efc',
    authDomain: 'viatu-f1efc.firebaseapp.com',
    storageBucket: 'viatu-f1efc.appspot.com',
    measurementId: 'G-8QDHDJ2PD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlar10E14DgtrV037IoEoioMCy1cMOruc',
    appId: '1:558821628686:android:cbb6fff612ea20c8ea155f',
    messagingSenderId: '558821628686',
    projectId: 'viatu-f1efc',
    storageBucket: 'viatu-f1efc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO0N3rh68xXAMRWanbwz02zmycO0GDkGo',
    appId: '1:558821628686:ios:d0868031478aad9fea155f',
    messagingSenderId: '558821628686',
    projectId: 'viatu-f1efc',
    storageBucket: 'viatu-f1efc.appspot.com',
    iosBundleId: 'com.itman.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO0N3rh68xXAMRWanbwz02zmycO0GDkGo',
    appId: '1:558821628686:ios:d0868031478aad9fea155f',
    messagingSenderId: '558821628686',
    projectId: 'viatu-f1efc',
    storageBucket: 'viatu-f1efc.appspot.com',
    iosBundleId: 'com.itman.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxDutOV77a-qTF3msZcQmpZXYXmFyrmIo',
    appId: '1:558821628686:web:5eeec265e7735b1cea155f',
    messagingSenderId: '558821628686',
    projectId: 'viatu-f1efc',
    authDomain: 'viatu-f1efc.firebaseapp.com',
    storageBucket: 'viatu-f1efc.appspot.com',
    measurementId: 'G-8Y391NYZS2',
  );
}
